"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
default-command = "log"
diff-editor = ":builtin"
diff-formatter = "delta"

[merge-tools.delta]
diff-expected-exit-codes = [0, 1]

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'

[aliases]
l = ["log", "-r", "(main..@):: | (main..@)-"]
tail = ["util", "exec", "--", "hwatch", "--color", "jj", "--ignore-working-copy", "log", "-n10", "-p", "--color=always"]
set-main = ["b", "s", "main", "-r", "git_head()"]
track-main = ["b", "t", "main@origin"]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]
f = ["git", "fetch"]
p = ["git", "push"]
cm = ["ci", "-m"]
d = ["desc"]
dm = ["d", "-m"]
